name: Display Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      # branch:
      #   description: 'Branch to choose'
      #   required: true
      #   default: 'main'
      country:
        description: 'Country'
        required: true
        type: choice
        options:
          - brazil
          - chile
        default: 'brazil'
      image_version:
        description: 'Version of the image to deploy'
        required: true
        default: 'latest'

jobs:
  display-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Display Inputs
      run: |
        echo "Branch: ${{ github.event.inputs.branch }}"
        echo "Country: ${{ github.event.inputs.country }}"
        echo "Image Version: ${{ github.event.inputs.image_version }}"
